AWSTemplateFormatVersion: 2010-09-09
Description: UPK Base Stack
Parameters:
  Version:
    Type: String
    AllowedValues:
      - 12.0.2
    Default: 12.0.2
  Mode:
    Type: String
    AllowedValues:
      - Normal
      - Debug
    Default: Normal
  Account:
    Type: String
    Default: Build
    AllowedValues:
      - Production
      - Production-DR
      - Build
      - PMO
  Release:
    Type: String
    Default: Development
    AllowedValues:
      - Copy
      - Development
      - Demo
      - Dress-Rehearsal
      - Integration-Test
      - Main
      - Performance-Monitor
      - Performance-Test
      - Payroll-Parallel-Test
      - System-Test
      - Test
      - Training
      - User-Acceptance-Test
      - UPK
  SequenceID:
    Type: String
    Default: '0'
    AllowedValues:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
  EncryptedAMI:
    Type: String
    Default: ami-fd0d4a85
  KeyPairName:
    Type: 'AWS::EC2::KeyPair::KeyName'
    Description: The Key Pair for EC2 Instances
    Default: ucpath-build-us-west-2
  DBInstanceClass:
    Type: String
    Default: db.r4.xlarge
  DBEngineVersion:
    Type: String
    Default: 12.1.0.2.v14
  DBSnapshotIdentifier:
    Description: The name or ARN of the DB snapshot to be used as the source
    Type: String
  DBMultiAZ:
    Type: String
    AllowedValues:
      - true
      - false
    Default: false
  DBMasterUsername:
    Type: String
    Default: UPKRDSADMIN
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.large
  FriendlyName:
    Description: A Friendly Name for the environment.
    Type: String
  Purpose:
    Description: User input describing the reason for the environment.
    Type: String
  FAU:
    Description: The Financial Accounting Unit (FAU). The cost center for the environment.
    Type: String
  ServiceNowTicket:
    Description: The Service Now Ticket for the requested deployment or change.
    Type: String
  LegacyID:
    Description: >-
      Optional, if the instance is a copy from OMCS, this will be the original
      OMCS name of the environment.
    Type: String
  ServiceOwner:
    Description: The Service Owner for the Environment.
    Type: String
  SourceDatabase:
    Description: The Source DB that was used to create the environment.
    Type: String
  SourceDate:
    Description: The Source Date of the DB Used.
    Type: String
  MaintenanceWindow:
    Description: The Predefined Maintenance Window
    Type: String
  RequestedBy:
    Description: The Requestor for the Instance.
    Type: String
  RequestedDate:
    Description: The Date the Instance was requested.
    Type: String
  DateCreated:
    Description: The Date the Instance was created.
    Type: String
  DBMasterUserPassword:
    Type: String
    NoEcho: true
  UPKDBUSRPWD:
    Type: String
    NoEcho: true
  UPKDBUSRAPPPWD:
    Type: String
    NoEcho: true
  UPKADMINPWD:
    Type: String
    NoEcho: true
  WebTierInternalFleetMinSize:
    Description: Minimum number of Web Servers
    Type: Number
    Default: 1
  WebTierInternalFleetMaxSize:
    Description: Maximum number of Web Servers
    Type: Number
    Default: 1
Mappings:
  Account2Parameter:
    Production:
      DBLower: prd
      DBUpper: PRD
      CIDR: 10.48.128.0/20
      RDS: crhanesnfdwj
      Bucket: ucpath-prod-us-west-2
      KeyPairName: ucpath-prod-us-west-2
      NetworkStack: ucpath-prod-network-VPC-1VL7QJZ2WZH5Y
      IamInstanceProfile: ucpath-prod-ec2
      R53: ucpath-prod.devops.universityofcalifornia.edu
      SSLCertificateArn: >-
        arn:aws:acm:us-west-2:011208821250:certificate/b4d550b2-0a15-4523-ac0c-62e7d04abe06
      OptionGroupName: prd-oracle-ee-12-1
      DBSecurityGroup: sg-fde4fb83
      S3KeyID: 3290ea94-247f-4a00-9385-c5e110874208
    Production-DR:
      CIDR: 10.48.144.0/20
    Build:
      DBLower: bld
      DBUpper: BLD
      CIDR: 10.48.160.0/20
      RDS: cfb3cut7jeem
      Bucket: ucpath-build-us-west-2
      KeyPairName: ucpath-build-us-west-2
      NetworkStack: network-VPC-1L2C0APMPYJXI
      IamInstanceProfile: 'arn:aws:iam::863914007401:instance-profile/ucpath-build-ec2'
      R53: ucpath-build.devops.universityofcalifornia.edu
      SSLCertificateArn: >-
        arn:aws:acm:us-west-2:863914007401:certificate/636e4421-25b9-46ec-bc5a-81eafd70fb71
      OptionGroupName: bld-oracle-ee-12-1
      DBSecurityGroup: sg-a8eef1d6
      S3KeyID: 8faccada-6580-4166-b3ec-41ea072d124a
      SMTPUserName: AKIAI77AP7Z245PUL3OQ
      SMTPUserPassword: '{V1.1}4xnBgID3HFb0ya6/0jg/nGYY8fQUAwlp//Pwfg1Ko8+7kjOVfC5i8I1X8giGC0/d'
    PMO:
      DBLower: pmo
      DBUpper: PMO
      CIDR: 10.48.176.0/20
      RDS: cseybontwdua
      Bucket: ucpath-pmo-us-west-2
      KeyPairName: ucpath-pmo-us-west-2
      NetworkStack: ucpath-pmo-network-VPC-G8U3L4H2I7XJ
      IamInstanceProfile: 'arn:aws:iam::111569475818:instance-profile/ucpath-pmo-ec2'
      R53: ucpath-pmo.devops.universityofcalifornia.edu
      SSLCertificateArn: >-
        arn:aws:acm:us-west-2:111569475818:certificate/bddc06ed-8018-45be-b831-1b07e67f2e68
      OptionGroupName: pmo-oracle-ee-12-1
      DBSecurityGroup: sg-79e7f807
      S3KeyID: 1168698a-5e34-4f92-ba28-73686a7ad772
      SMTPUserName: AKIAJTHH4RBLMC2X6F4Q
      SMTPUserPassword: '{V1.1}JNkoHPlzMC8x3ytfXVOcOwTz6gz4PEbqvk4IN/RiUGDfedQ3b2+qMgaax1zHit0+'
  App2Tag:
    PeopleSoft:
      DBLower: h
      DBUpper: H
    SOA:
      DBLower: s
      DBUpper: S
    DDODS:
      DBLower: o
      DBUpper: O
    Elasticsearch:
      DBLower: e
      DBUpper: E
    UPK:
      DBLower: u
      DBUpper: U      
  Rel2Tag:
    Copy:
      DBLower: cpy
      DBUpper: CPY
    Development:
      DBLower: dev
      DBUpper: DEV
    Demo:
      DBLower: dmo
      DBUpper: DMO
    Dress-Rehearsal:
      DBLower: reh
      DBUpper: REH
    Integration-Test:
      DBLower: int
      DBUpper: INT
    Main:
      DBLower: mne
      DBUpper: MNE
    Performance-Monitor:
      DBLower: ppm
      DBUpper: PPM
    Performance-Test:
      DBLower: pft
      DBUpper: PFT
    Payroll-Parallel-Test:
      DBLower: ppt
      DBUpper: PPT
    System-Test:
      DBLower: sys
      DBUpper: SYS
    Test:
      DBLower: tst
      DBUpper: TST
    Training:
      DBLower: trn
      DBUpper: TRN
    User-Acceptance-Test:
      DBLower: uat
      DBUpper: UAT


      
Resources:
  DBStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        EnvStack: !Ref 'AWS::StackName'
        NetworkStack: !FindInMap 
          - Account2Parameter
          - !Ref Account
          - NetworkStack
        AccountCIDR: !FindInMap 
          - Account2Parameter
          - !Ref Account
          - CIDR
        R53HostedZone: !FindInMap 
          - Account2Parameter
          - !Ref Account
          - R53
        DBInstanceClass: !Ref DBInstanceClass
        DBName: !Join 
          - ''
          - - !FindInMap 
              - App2Tag
              - UPK
              - DBUpper
            - !FindInMap 
              - Account2Parameter
              - !Ref Account
              - DBUpper
            - !FindInMap 
              - Rel2Tag
              - !Ref Release
              - DBUpper
            - !Ref SequenceID
        DBSnapshotIdentifier: !Ref DBSnapshotIdentifier
        Engine: oracle-ee
        EngineVersion: !Ref DBEngineVersion
        MasterUsername: !Ref DBMasterUsername
        MasterUserPassword: !Ref DBMasterUserPassword
        StorageType: gp2
        AllocatedStorage: '1000'
        MultiAZ: !Ref DBMultiAZ
        DBPort: '1521'
        LicenseModel: bring-your-own-license
        CharacterSetName: AL32UTF8
        OptionGroupName: !FindInMap 
          - Account2Parameter
          - !Ref Account
          - OptionGroupName
        DBSecurityGroup: !FindInMap 
          - Account2Parameter
          - !Ref Account
          - DBSecurityGroup
      TemplateURL: !Join 
        - ''
        - - 'https://s3.amazonaws.com/'
          - !FindInMap 
            - Account2Parameter
            - !Ref Account
            - Bucket
          - /config/cloudformation/app/upk/
          - !Ref Version
          - /upk-db.yml
      Tags:
        - Key: 'ucpath:ApplicationDBEndpoint'
          Value: !Join 
            - ''
            - - !FindInMap 
                - App2Tag
                - UPK
                - DBLower
              - !FindInMap 
                - Account2Parameter
                - !Ref Account
                - DBLower
              - !FindInMap 
                - Rel2Tag
                - !Ref Release
                - DBLower
              - !Ref SequenceID
              - .
              - !FindInMap 
                - Account2Parameter
                - !Ref Account
                - RDS
              - '.us-west-2.rds.amazonaws.com:1521'
        - Key: 'ucpath:OEMURL'
          Value: !Join 
            - ''
            - - 'https://'
              - !FindInMap 
                - App2Tag
                - UPK
                - DBLower
              - !FindInMap 
                - Account2Parameter
                - !Ref Account
                - DBLower
              - !FindInMap 
                - Rel2Tag
                - !Ref Release
                - DBLower
              - !Ref SequenceID
              - .
              - !FindInMap 
                - Account2Parameter
                - !Ref Account
                - RDS
              - '.us-west-2.rds.amazonaws.com:5500/em'
        - Key: 'ucpath:Tier'
          Value: DB
        - Key: 'ucpath:Account'
          Value: !Ref Account
        - Key: 'ucpath:ApplicationName'
          Value: PeopleSoft
        - Key: 'ucpath:Release'
          Value: !Ref Release
        - Key: 'ucpath:Purpose'
          Value: !Ref Purpose
        - Key: 'ucpath:FAU'
          Value: !Ref FAU
        - Key: 'ucpath:ServiceNowTicket'
          Value: !Ref ServiceNowTicket
        - Key: 'ucpath:FriendlyName'
          Value: !Ref FriendlyName
        - Key: 'ucpath:LegacyID'
          Value: !Ref LegacyID
        - Key: 'ucpath:ServiceOwner'
          Value: !Ref ServiceOwner
        - Key: 'ucpath:SequenceID'
          Value: !Ref SequenceID
        - Key: 'ucpath:SourceDatabase'
          Value: !Ref SourceDatabase
        - Key: 'ucpath:SourceDate'
          Value: !Ref SourceDate
        - Key: 'ucpath:MaintenanceWindow'
          Value: !Ref MaintenanceWindow
        - Key: 'ucpath:RequestedBy'
          Value: !Ref RequestedBy
        - Key: 'ucpath:RequestedDate'
          Value: !Ref RequestedDate
        - Key: 'ucpath:DateCreated'
          Value: !Ref DateCreated
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 5d10c30d-5c4f-4149-8794-4d1ea8b2c25b
  AppStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:     
        Version: !Ref Version
        Mode: !Ref Mode
        DBLower: !Join 
          - ''
          - - !FindInMap 
              - App2Tag
              - UPK
              - DBLower
            - !FindInMap 
              - Account2Parameter
              - !Ref Account
              - DBLower
            - !FindInMap 
              - Rel2Tag
              - !Ref Release
              - DBLower
            - !Ref SequenceID
        DBUpper: !Join 
          - ''
          - - !FindInMap 
              - App2Tag
              - UPK
              - DBUpper
            - !FindInMap 
              - Account2Parameter
              - !Ref Account
              - DBUpper
            - !FindInMap 
              - Rel2Tag
              - !Ref Release
              - DBUpper
            - !Ref SequenceID
        EnvStack: !Ref 'AWS::StackName'
        NetworkStack: !FindInMap 
          - Account2Parameter
          - !Ref Account
          - NetworkStack
        AccountCIDR: !FindInMap 
          - Account2Parameter
          - !Ref Account
          - CIDR
        Bucket: !FindInMap 
          - Account2Parameter
          - !Ref Account
          - Bucket
        RDSURL: !Join 
          - ''
          - - !FindInMap 
              - App2Tag
              - UPK
              - DBLower
            - !FindInMap 
              - Account2Parameter
              - !Ref Account
              - DBLower
            - !FindInMap 
              - Rel2Tag
              - !Ref Release
              - DBLower
            - !Ref SequenceID
            - .
            - !FindInMap 
              - Account2Parameter
              - !Ref Account
              - RDS
            - .
            - !Ref 'AWS::Region'
            - .rds.amazonaws.com
        R53HostedZone: !FindInMap 
          - Account2Parameter
          - !Ref Account
          - R53
        EncryptedAMI: !Ref EncryptedAMI
        
        IamInstanceProfile: !FindInMap 
          - Account2Parameter
          - !Ref Account
          - IamInstanceProfile
        KeyPairName: !FindInMap 
          - Account2Parameter
          - !Ref Account
          - KeyPairName
        DBMasterUserPassword: !Ref DBMasterUserPassword
        UPKDBUSRPWD: !Ref UPKDBUSRPWD
        UPKDBUSRAPPPWD: !Ref UPKDBUSRAPPPWD
        UPKADMINPWD: !Ref UPKADMINPWD
        InstanceType: !Ref InstanceType
        EC2URL: !Join 
          - ''
          - - !FindInMap 
              - App2Tag
              - UPK
              - DBLower
            - !FindInMap 
              - Account2Parameter
              - !Ref Account
              - DBLower
            - !FindInMap 
              - Rel2Tag
              - !Ref Release
              - DBLower
            - !Ref SequenceID
            - .
            - !FindInMap 
              - Account2Parameter
              - !Ref Account
              - R53
        SSLCertificateArn: !FindInMap 
          - Account2Parameter
          - !Ref Account
          - SSLCertificateArn
        WebTierInternalFleetMinSize: !Ref WebTierInternalFleetMinSize
        WebTierInternalFleetMaxSize: !Ref WebTierInternalFleetMaxSize
      TemplateURL: !Join 
        - ''
        - - 'https://s3.amazonaws.com/'
          - !FindInMap 
            - Account2Parameter
            - !Ref Account
            - Bucket
          - /config/cloudformation/app/upk/
          - !Ref Version
          - /upk-app.yml
      Tags:
        - Key: 'ucpath:ApplicationURL'
          Value: !Join 
            - ''
            - - 'https://'
              - !FindInMap 
                - App2Tag
                - UPK
                - DBLower
              - !FindInMap 
                - Account2Parameter
                - !Ref Account
                - DBLower
              - !FindInMap 
                - Rel2Tag
                - !Ref Release
                - DBLower
              - !Ref SequenceID
              - .
              - !FindInMap 
                - Account2Parameter
                - !Ref Account
                - R53
              - /
              - !FindInMap 
                - App2Tag
                - UPK
                - DBUpper
              - !FindInMap 
                - Account2Parameter
                - !Ref Account
                - DBUpper
              - !FindInMap 
                - Rel2Tag
                - !Ref Release
                - DBUpper
              - !Ref SequenceID
              - /signon.html
        - Key: 'ucpath:ApplicationDBEndpoint'
          Value: !Join 
            - ''
            - - !FindInMap 
                - App2Tag
                - UPK
                - DBLower
              - !FindInMap 
                - Account2Parameter
                - !Ref Account
                - DBLower
              - !FindInMap 
                - Rel2Tag
                - !Ref Release
                - DBLower
              - !Ref SequenceID
              - .
              - !FindInMap 
                - Account2Parameter
                - !Ref Account
                - RDS
              - '.us-west-2.rds.amazonaws.com:1521'
        - Key: 'ucpath:OEMURL'
          Value: !Join 
            - ''
            - - 'https://'
              - !FindInMap 
                - App2Tag
                - UPK
                - DBLower
              - !FindInMap 
                - Account2Parameter
                - !Ref Account
                - DBLower
              - !FindInMap 
                - Rel2Tag
                - !Ref Release
                - DBLower
              - !Ref SequenceID
              - .
              - !FindInMap 
                - Account2Parameter
                - !Ref Account
                - RDS
              - '.us-west-2.rds.amazonaws.com:5500/em'
        - Key: 'ucpath:Tier'
          Value: App
        - Key: 'ucpath:Account'
          Value: !Ref Account
        - Key: 'ucpath:ApplicationName'
          Value: PeopleSoft
        - Key: 'ucpath:Release'
          Value: !Ref Release
        - Key: 'ucpath:Purpose'
          Value: !Ref Purpose
        - Key: 'ucpath:FAU'
          Value: !Ref FAU
        - Key: 'ucpath:ServiceNowTicket'
          Value: !Ref ServiceNowTicket
        - Key: 'ucpath:FriendlyName'
          Value: !Ref FriendlyName
        - Key: 'ucpath:LegacyID'
          Value: !Ref LegacyID
        - Key: 'ucpath:ServiceOwner'
          Value: !Ref ServiceOwner
        - Key: 'ucpath:SequenceID'
          Value: !Ref SequenceID
        - Key: 'ucpath:SourceDatabase'
          Value: !Ref SourceDatabase
        - Key: 'ucpath:SourceDate'
          Value: !Ref SourceDate
        - Key: 'ucpath:MaintenanceWindow'
          Value: !Ref MaintenanceWindow
        - Key: 'ucpath:RequestedBy'
          Value: !Ref RequestedBy
        - Key: 'ucpath:RequestedDate'
          Value: !Ref RequestedDate
        - Key: 'ucpath:DateCreated'
          Value: !Ref DateCreated
    Metadata:
      'AWS::CloudFormation::Designer':
        id: ad96aa6b-6ce3-40cc-a645-bbf7c95caec6
    DependsOn:
      - DBStack
